QUESTIONS = {
    "science": [
        {"q": "What is the chemical symbol for water?", "options": ["H2O", "CO2", "O2", "H2"], "answer": 0},
        {"q": "How many chromosomes do humans have?", "options": ["23", "46", "48", "44"], "answer": 1},
        {"q": "What is the powerhouse of the cell?", "options": ["Nucleus", "Ribosome", "Mitochondria", "Golgi Body"], "answer": 2},
        {"q": "What gas do plants absorb from the atmosphere?", "options": ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], "answer": 2},
        {"q": "What is the hardest natural substance on Earth?", "options": ["Gold", "Iron", "Diamond", "Quartz"], "answer": 2},
        {"q": "How many bones are in the adult human body?", "options": ["196", "206", "216", "226"], "answer": 1},
        {"q": "What is the speed of light (approx)?", "options": ["3×10⁸ m/s", "3×10⁶ m/s", "3×10⁴ m/s", "3×10¹⁰ m/s"], "answer": 0},
        {"q": "Which planet is known as the Red Planet?", "options": ["Venus", "Jupiter", "Mars", "Saturn"], "answer": 2},
        {"q": "What is the most abundant gas in Earth's atmosphere?", "options": ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"], "answer": 2},
        {"q": "DNA stands for?", "options": ["Deoxyribonucleic Acid", "Diribonucleic Acid", "Deoxyribose Acid", "None of these"], "answer": 0},
    ],
    "math": [
        {"q": "What is the value of π (pi) to 2 decimal places?", "options": ["3.14", "3.41", "3.12", "3.16"], "answer": 0},
        {"q": "What is the square root of 144?", "options": ["11", "12", "13", "14"], "answer": 1},
        {"q": "What is 15% of 200?", "options": ["25", "30", "35", "40"], "answer": 1},
        {"q": "Solve: 2x + 5 = 15. What is x?", "options": ["4", "5", "6", "7"], "answer": 1},
        {"q": "What is the sum of interior angles in a triangle?", "options": ["90°", "180°", "270°", "360°"], "answer": 1},
        {"q": "What is 7 factorial (7!)?", "options": ["2520", "5040", "720", "40320"], "answer": 1},
        {"q": "What is the derivative of x²?", "options": ["x", "2x", "x²", "2"], "answer": 1},
        {"q": "What is log₁₀(1000)?", "options": ["2", "3", "4", "10"], "answer": 1},
        {"q": "What is the area of a circle with radius 7? (π≈3.14)", "options": ["153.86", "143.86", "163.86", "133.86"], "answer": 0},
        {"q": "What does the Pythagorean theorem state?", "options": ["a+b=c", "a²+b²=c²", "a²-b²=c", "ab=c²"], "answer": 1},
    ],
    "physics": [
        {"q": "What is Newton's second law of motion?", "options": ["F=mv", "F=ma", "F=m/a", "F=a/m"], "answer": 1},
        {"q": "What is the SI unit of electric current?", "options": ["Volt", "Watt", "Ampere", "Ohm"], "answer": 2},
        {"q": "What is the SI unit of force?", "options": ["Joule", "Pascal", "Newton", "Watt"], "answer": 2},
        {"q": "What is the formula for kinetic energy?", "options": ["mgh", "½mv²", "mv", "Fd"], "answer": 1},
        {"q": "What is Ohm's Law?", "options": ["V=IR", "V=I/R", "V=I+R", "V=I²R"], "answer": 0},
        {"q": "What is the acceleration due to gravity on Earth?", "options": ["8.9 m/s²", "9.8 m/s²", "10.8 m/s²", "11 m/s²"], "answer": 1},
        {"q": "What type of wave is sound?", "options": ["Transverse", "Electromagnetic", "Longitudinal", "Surface"], "answer": 2},
        {"q": "What is the SI unit of energy?", "options": ["Watt", "Newton", "Joule", "Pascal"], "answer": 2},
        {"q": "What is the frequency of AC supply in most countries?", "options": ["50 Hz only", "60 Hz only", "50 Hz or 60 Hz", "100 Hz"], "answer": 2},
        {"q": "What does E=mc² represent?", "options": ["Kinetic energy", "Mass-energy equivalence", "Potential energy", "Wave energy"], "answer": 1},
    ],
}
